import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/project/Footer";
import { Navbar } from "@/components/project/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased dark min-h-screen flex flex-col bg-background`}
        >
        <Navbar />
        <div className="flex-1 max-w-3xl w-full mx-auto space-y-12 flex flex-col justify-center">
            {children}
            <Footer />
        </div>
        </body>
        </html>
    );
}
